name: 'Alibaba Cloud Container Registry (ACR) Login'
description: 'Log in to a container registry'
inputs: 
  username:
    description: 'Container registry username'
    required: true
    default: ''
  password:
    description: 'Container registry password'
    required: true
    default: ''
  access-key-id:
    description: 'Access key id'
    required: true
    default: ''
  access-key-secret:
    description: 'Access key secret'
    required: true
    default: ''
  region-id:
    description: 'Region id'
    required: true
    default: 'cn-hangzhou'
  instance-id:
    description: 'Registry instance id'
    required:true
    default: ''
  login-server:
    description: 'Container registry server url'
    required: true
    default: ''
branding:
  color: 'green'
  icon: 'anchor'
runs:
  using: 'node12'
  main: 'dist/index.js'
